client:
  service-url:
    defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: ORDER-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://admin:Hsenidbhu1@atlas-cluster.c5hzrwm.mongodb.net/?retryWrites=true&w=majority
      host: localhost
      port: 27017
      database: orderdb
      repositories:
        type: auto

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect


